#-------------------------------
# General Site Settings
title: ICED-A3
logo: ICED-A3_8dpi.gif # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Alex Rodriguez
  image: 02.jpg
  say-hello: Hola, Soy <strong>Claudio Durán-Alarcón</strong>
  bio:  ¡Hablemos de cosas heladas en la Tierra! me refiero a glaciares, grandes campos de hielo y nieve, y también a las pequeñas partículas sólidos presentes en la Atmósfera, como cristales de hielo y copos de nieve. En este blog, trataremos temas relacionados con clima, meteorología, métodos de observación, modelación e impactos en la sociedad, con un especial énfasis en las ciencias Polares y Alpinas. Comenta y comparte este contenido si te gusta. ¡Muchas gracias por tu visita!


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
