#-------------------------------
# General Site Settings
title: ICED-A3
logoT: ICED-A3_8dpi.gif # You can add own logo.
logo: ICEDA3_logo_final4.png # You can add own logo.
description: ICED-A3 is the personal blog of Claudio Durán-Alarcón.


#-------------------------------
# Author Settings
author:
  name: Claudio Durán-Alarcón
  image: dscn0059-copie.jpg
  say-hello: <strong>Claudio Durán-Alarcón</strong>
  bio:  ¡Hablemos de cosas heladas en la Tierra! me refiero a glaciares, grandes campos de hielo y nieve, y también a las pequeñas partículas sólidos presentes en la Atmósfera, como cristales de hielo y copos de nieve. En este blog, trataremos temas relacionados con clima, meteorología, métodos de observación, modelación e impactos en la sociedad, con un especial énfasis en las ciencias Polares y Alpinas. Comenta y comparte este contenido si te gusta. ¡Muchas gracias por tu visita!


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
instagram: https://instagram.com/ # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: iced-a3 # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
